
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS CATEGORIES;

CREATE TABLE CATEGORIES (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE PRODUCTS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    CATEGORY_ID INT,
    PRICE DOUBLE,
    STOCK_QUANTITY INT,
    IMAGE_URL VARCHAR(255),
    CREATED_AT VARCHAR(50),
    UPDATED_AT VARCHAR(50)
);
