/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsu.cad.lab;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.PropertySource;

import ru.bsu.cad.lab.config.AppConfig;
import ru.bsu.cad.lab.renderer.Renderer;

@SpringBootApplication
@PropertySource("classpath:application.properties")
public class App {
    public static void main(String[] args) {
        try {
            AnnotationConfigApplicationContext context = 
                new AnnotationConfigApplicationContext(AppConfig.class);
            Renderer renderer = context.getBean(Renderer.class);
            renderer.render();
            context.close();
        } catch (Exception e) {
            System.err.println("Application failed: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }
}
