/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import ru.bsuedu.cad.lab.app.OrderClient;
import ru.bsuedu.cad.lab.app.TableConfiguration;

public class App {

	public static void main(String[] args) {
		var ctx = new AnnotationConfigApplicationContext(TableConfiguration.class);
		var client = ctx.getBean(OrderClient.class);
		client.run();
		ctx.close();
	}
}
