/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;

import org.junit.jupiter.api.Test;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import ru.bsuedu.cad.lab.renderer.Renderer;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void contextLoadsAndRendererExists() {
        ApplicationContext context = new AnnotationConfigApplicationContext(App.class);
        Renderer renderer = context.getBean(Renderer.class);
        assertNotNull(renderer);
    }
}