CREATE TABLE IF NOT EXISTS customers (
                                         customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    address VARCHAR(500)
    );

CREATE TABLE IF NOT EXISTS products (
                                        product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(19,2) NOT NULL,
    stock_quantity INT NOT NULL,
    image_url VARCHAR(500),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS orders (
                                      order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      customer_id BIGINT NOT NULL,
                                      order_date TIMESTAMP NOT NULL,
                                      total_price DECIMAL(19,2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    shipping_address VARCHAR(500),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
    );

CREATE TABLE IF NOT EXISTS order_details (
                                             order_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             order_id BIGINT NOT NULL,
                                             product_id BIGINT NOT NULL,
                                             quantity INT NOT NULL,
                                             price DECIMAL(19,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
    );