/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {
	public static void main(String[] args) {
		AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(
				SpringConfig.class);

		// ConsoleTableRenderer table = context.getBean("consoleTableRenderer",
		// ConsoleTableRenderer.class);
		// table.render();
		ConsoleTableRenderer r = context.getBean("consoleTableRenderer", ConsoleTableRenderer.class);
		r.render();
		context.close();
	}
}
