/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("javax.annotation:javax.annotation-api:1.3.2")
    implementation("org.springframework:spring-aspects:5.3.22")
    implementation("org.springframework:spring-context:6.2.2")
    implementation("org.springframework:spring-core:6.2.2")
    implementation("org.springframework:spring-beans:6.2.2")
    implementation("org.springframework:spring-context-support:6.2.2")
    implementation("com.h2database:h2:2.2.220")
    implementation("org.springframework:spring-jdbc:6.2.2")
    implementation("ch.qos.logback:logback-classic:1.4.14")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "ru.bsuedu.cad.lab.MainApp"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
