/*
 * This source file was generated by the Gradle 'init' task
 */
// Основное приложение с настройкой DataSource и JPA

package ru.bsuedu.cad.lab.app;

import org.springframework.context.annotation.*;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import javax.sql.DataSource;
import com.zaxxer.hikari.HikariDataSource;
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean;
import org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter;
import java.util.Properties;
import ru.bsuedu.cad.lab.service.OrderService;
import ru.bsuedu.cad.lab.repository.CustomerRepository;
import ru.bsuedu.cad.lab.repository.ProductRepository;
import ru.bsuedu.cad.lab.entity.Customer;
import ru.bsuedu.cad.lab.entity.Product;
import org.springframework.orm.jpa.JpaTransactionManager;
import org.springframework.transaction.PlatformTransactionManager;

import java.util.List;

// Главный класс запуска приложения
public class App {
    public static void main(String[] args) {
    
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
        System.out.println("✅ Приложение успешно запущено.");

   
        OrderService orderService = context.getBean(OrderService.class);
        CustomerRepository customerRepository = context.getBean(CustomerRepository.class);
        ProductRepository productRepository = context.getBean(ProductRepository.class);

        Customer customer = customerRepository.findById(1).orElseThrow(() -> new RuntimeException("Клиент не найден"));
        List<Product> products = productRepository.findAll().subList(0, 2); 

        orderService.createOrder(customer, products);

        context.close();
    }
}

